// ============================================================
//  questions.js  -  the "Earn shots" question bank
//
//  To add a question, copy one block and change it:
//    id       unique short text
//    level    "easy" (1 shot), "medium" (2 shots) or "hard" (3 shots)
//    code     optional lines of pseudocode shown above the question
//    q        the question
//    options  exactly 4 answers
//    answer   index of the correct option (0 = first)
//    explain  shown after answering
// ============================================================

export const REWARD = { easy: 1, medium: 2, hard: 3 };

export const QUESTIONS = [
  // ---------------- easy: 1 shot ----------------
  { id: "e-assign", level: "easy",
    q: "Which symbol does Cambridge pseudocode use to assign a value to a variable?",
    options: ["←", "=", "==", ":="], answer: 0,
    explain: "Assignment uses ←, as in Score ← 0. The = sign is used for comparing." },
  { id: "e-bool", level: "easy",
    q: "Which data type holds only TRUE or FALSE?",
    options: ["BOOLEAN", "CHAR", "STRING", "INTEGER"], answer: 0,
    explain: "A BOOLEAN can only be TRUE or FALSE." },
  { id: "e-age", level: "easy",
    q: "What is the best data type for a person's age in whole years?",
    options: ["INTEGER", "REAL", "CHAR", "BOOLEAN"], answer: 0,
    explain: "Whole numbers are stored as INTEGER. REAL is for numbers with a decimal part." },
  { id: "e-char", level: "easy",
    q: "What is the best data type for a single letter such as 'Y'?",
    options: ["CHAR", "STRING", "INTEGER", "REAL"], answer: 0,
    explain: "A single character is a CHAR. A STRING holds zero or more characters." },
  { id: "e-endif", level: "easy",
    q: "Which keyword closes an IF statement?",
    options: ["ENDIF", "END", "NEXT", "STOP"], answer: 0,
    explain: "IF ... THEN ... ELSE ... ENDIF." },
  { id: "e-repeat", level: "easy",
    q: "Which loop always runs its statements at least once?",
    options: ["REPEAT ... UNTIL", "WHILE ... ENDWHILE", "FOR ... NEXT", "IF ... ENDIF"], answer: 0,
    explain: "REPEAT checks its condition at the end, so the body always runs at least once." },
  { id: "e-count", level: "easy",
    q: "Which loop is best when you know exactly how many times to repeat?",
    options: ["FOR ... NEXT", "WHILE ... ENDWHILE", "REPEAT ... UNTIL", "CASE ... ENDCASE"], answer: 0,
    explain: "FOR ... NEXT is a count-controlled loop." },
  { id: "e-trace1", level: "easy",
    code: ["X ← 4", "Y ← X + 3", "OUTPUT Y"],
    q: "What is output?",
    options: ["7", "4", "3", "43"], answer: 0,
    explain: "Y gets 4 + 3, which is 7." },
  { id: "e-output", level: "easy",
    q: "Which statement displays a value on the screen?",
    options: ["OUTPUT", "INPUT", "DECLARE", "RETURN"], answer: 0,
    explain: "OUTPUT displays a value. INPUT reads one in." },
  { id: "e-mod", level: "easy",
    q: "What is the value of MOD(17, 5)?",
    options: ["2", "3", "3.4", "12"], answer: 0,
    explain: "MOD gives the remainder. 17 ÷ 5 is 3 remainder 2." },

  // ---------------- medium: 2 shots ----------------
  { id: "m-div", level: "medium",
    q: "What is the value of DIV(17, 5)?",
    options: ["3", "2", "3.4", "4"], answer: 0,
    explain: "DIV gives the whole-number part of the division: 17 ÷ 5 = 3 remainder 2." },
  { id: "m-total", level: "medium",
    code: ["Total ← 0", "FOR Count ← 1 TO 4", "    Total ← Total + Count", "NEXT Count", "OUTPUT Total"],
    q: "What is output?",
    options: ["10", "4", "5", "15"], answer: 0,
    explain: "Total becomes 1 + 2 + 3 + 4 = 10." },
  { id: "m-length", level: "medium",
    q: 'What is the value of LENGTH("Brunei")?',
    options: ["6", "5", "7", "1"], answer: 0,
    explain: "B-r-u-n-e-i is 6 characters." },
  { id: "m-substr", level: "medium",
    q: 'What is the value of SUBSTRING("Computer", 1, 4)?',
    options: ['"Comp"', '"ompu"', '"Compu"', '"uter"'], answer: 0,
    explain: "Start at character 1 and take 4 characters: C-o-m-p." },
  { id: "m-ucase", level: "medium",
    q: 'What is the value of UCASE("chms")?',
    options: ['"CHMS"', '"Chms"', '"chms"', "4"], answer: 0,
    explain: "UCASE changes every letter to upper case." },
  { id: "m-while", level: "medium",
    code: ["X ← 10", "WHILE X > 3 DO", "    X ← X - 4", "ENDWHILE", "OUTPUT X"],
    q: "What is output?",
    options: ["2", "6", "3", "-2"], answer: 0,
    explain: "X goes 10, 6, 2. When X is 2 the condition X > 3 is false, so the loop stops." },
  { id: "m-oddeven", level: "medium",
    code: ["Num ← 7", "IF MOD(Num, 2) = 0", "  THEN", '    OUTPUT "Even"', "  ELSE", '    OUTPUT "Odd"', "ENDIF"],
    q: "What is output?",
    options: ["Odd", "Even", "7", "Nothing"], answer: 0,
    explain: "MOD(7, 2) is 1, not 0, so the ELSE branch runs." },
  { id: "m-range", level: "medium",
    q: "Which validation check makes sure a test mark is between 0 and 100?",
    options: ["Range check", "Length check", "Presence check", "Format check"], answer: 0,
    explain: "A range check tests that a value is between a lower and an upper limit." },
  { id: "m-loopcount", level: "medium",
    code: ["FOR i ← 2 TO 6", '    OUTPUT "Hi"', "NEXT i"],
    q: 'How many times is "Hi" output?',
    options: ["5", "4", "6", "2"], answer: 0,
    explain: "i takes the values 2, 3, 4, 5 and 6. That's 5 times." },
  { id: "m-array", level: "medium",
    code: ["DECLARE Scores : ARRAY[1:10] OF INTEGER"],
    q: "How many values can the array Scores hold?",
    options: ["10", "9", "11", "1"], answer: 0,
    explain: "Indexes 1 to 10 give 10 elements." },
  { id: "m-init", level: "medium",
    q: "Why is Total ← 0 written before a totalling loop?",
    options: ["So the running total starts from zero", "To stop the loop", "To declare Total as a REAL", "To output the total"], answer: 0,
    explain: "This is initialisation. Without it, Total would start with no value." },
  { id: "m-until", level: "medium",
    q: 'A REPEAT loop should stop once Password is "open". Which line ends it?',
    options: ['UNTIL Password = "open"', 'UNTIL Password <> "open"', 'WHILE Password = "open"', 'ENDREPEAT Password'], answer: 0,
    explain: "REPEAT loops finish when the UNTIL condition becomes TRUE." },

  // ---------------- hard: 3 shots ----------------
  { id: "h-count3", level: "hard",
    code: ["Count ← 0", "FOR i ← 1 TO 10", "    IF MOD(i, 3) = 0", "      THEN", "        Count ← Count + 1", "    ENDIF", "NEXT i", "OUTPUT Count"],
    q: "What is output?",
    options: ["3", "10", "4", "18"], answer: 0,
    explain: "Only 3, 6 and 9 divide exactly by 3, so Count ends at 3." },
  { id: "h-swap", level: "hard",
    code: ["A ← 5", "B ← 2", "A ← A + B", "B ← A - B", "A ← A - B", "OUTPUT A, \" \", B"],
    q: "What is output?",
    options: ["2 5", "5 2", "7 5", "2 7"], answer: 0,
    explain: "A becomes 7, then B becomes 7 - 2 = 5, then A becomes 7 - 5 = 2. The values have swapped." },
  { id: "h-max", level: "hard",
    code: ["// Nums[1] to Nums[4] hold 4, 9, 2, 7", "Max ← Nums[1]", "FOR i ← 2 TO 4", "    IF Nums[i] > Max", "      THEN", "        Max ← Nums[i]", "    ENDIF", "NEXT i", "OUTPUT Max"],
    q: "What is output?",
    options: ["9", "7", "4", "2"], answer: 0,
    explain: "This finds the largest value. Max goes 4, then 9, and nothing after is bigger." },
  { id: "h-nested", level: "hard",
    code: ["Total ← 0", "FOR i ← 1 TO 3", "    FOR j ← 1 TO 2", "        Total ← Total + 1", "    NEXT j", "NEXT i", "OUTPUT Total"],
    q: "What is output?",
    options: ["6", "5", "3", "9"], answer: 0,
    explain: "The inner loop runs 2 times for each of the 3 outer loops: 3 × 2 = 6." },
  { id: "h-func", level: "hard",
    code: ["FUNCTION Double(N : INTEGER) RETURNS INTEGER", "    RETURN N * 2", "ENDFUNCTION", "", "OUTPUT Double(Double(3))"],
    q: "What is output?",
    options: ["12", "6", "9", "18"], answer: 0,
    explain: "Double(3) is 6, then Double(6) is 12." },
  { id: "h-procfunc", level: "hard",
    q: "What is the key difference between a function and a procedure?",
    options: ["A function returns a value", "A procedure returns a value", "Only procedures take parameters", "Functions can't use loops"], answer: 0,
    explain: "A function RETURNS a value to where it was called. A procedure doesn't." },
  { id: "h-banana", level: "hard",
    code: ['Word ← "BANANA"', "Count ← 0", "FOR i ← 1 TO LENGTH(Word)", '    IF SUBSTRING(Word, i, 1) = "A"', "      THEN", "        Count ← Count + 1", "    ENDIF", "NEXT i", "OUTPUT Count"],
    q: "What is output?",
    options: ["3", "2", "6", "1"], answer: 0,
    explain: "The loop checks each letter of BANANA and counts the 3 A's." },
  { id: "h-round", level: "hard",
    q: "What is the value of ROUND(7.456, 1)?",
    options: ["7.5", "7.4", "7.46", "8"], answer: 0,
    explain: "Round to 1 decimal place: 7.456 → 7.5." },
  { id: "h-repeat", level: "hard",
    code: ["X ← 1", "REPEAT", "    X ← X * 3", "UNTIL X > 20", "OUTPUT X"],
    q: "What is output?",
    options: ["27", "9", "20", "81"], answer: 0,
    explain: "X goes 3, 9, 27. After 27 the condition X > 20 is TRUE, so the loop ends." },
  { id: "h-linear", level: "hard",
    q: "A linear search looks for a value in an unsorted array. What does it do?",
    options: ["Checks each element in turn from the start", "Jumps to the middle element first", "Sorts the array first", "Only checks the last element"], answer: 0,
    explain: "A linear search checks elements one by one until it finds the value or reaches the end." },
];
